#!/bin/bash
#
#
##
echo -n "Sisesta kasutajanimi: "
read kasutaja
andmebaas=$kasutaja'_andmebaas'
date=$(date +%y-%m-%d.%H-%M.$andmebaas.backup.sql)
mysqldump  --user=root --password=root $andmebaas > /mysql_backup/$date.$andmebaas.backup.sql
#
#
## L6pp
