#!/bin/bash
#
# 

failinimi="kasutajad"
	for rida in $(cat $failinimi)
	do
	kasutajanimi=$(echo "$rida" | cut -f1 -d:)
	sh lisa_kasutaja $kasutajanimi
	echo "$rida" | chpasswd
done


#############EELMINE SKRIPT#¤###################
# if [ -f kasutajad -a -r kasutajad ]; then
#		echo Fail on okidoki"
# for rida in $(cat kasutajad)
#  do
##Selle osaga peaks esile tulema faili sisu
#	sh lisa_kasutaja $rida
#	done
#else
#	echo Fail ei ole okidoki"
#fi
