#!/bin/bash
#
#
# kysib kasutajanime
echo "Sisesta kasutajanimi"
read kasutaja
andmebaas=$kasutaja'_andmebaas'
parool=$(openssl rand -hex 8)
mycnf=/home/$kasutaja/.my.cnf
######### MYSQL
	mysql --user=root --password=root -e "create user '$kasutaja' identified by '$parool';create database $andmebaas; use $andmebaas; grant all privileges on $andmebaas.* to $kasutaja;"
		echo -e "[client]\nuser=$kasutaja\npassword=$parool" > $mycnf
			chmod 644 $mycnf
